# 복습과제

In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd

In [9]:
call = pd.read_csv('call_data_scaled.csv')
call_data = pd.read_csv('call_data.csv')

### 해지여부를 예측하는 모델링
- 분류
- 0,1 이진분류
- 이진분류를 하는 모델링
- LGBM, XGM, CAT, RF 등 다양하게 분류에 대한 알고리즘을 사용
- y값은 전화해지여부
- x값은 나머지

In [10]:
call = call.drop(['Unnamed: 0'], axis=1)
call

가입일   음성사서함이용    주간통화시간    주간통화횟수    주간통화요금    저녁통화시간    저녁통화횟수  \
0      1.278788 -0.045455 -2.017964 -0.181481 -0.162791  0.387387 -0.323529   
1     -0.703030  3.590909  1.345808  1.522222  2.460465  0.396396  1.573529   
2     -0.151515  1.227273  0.724551  1.522222  0.158140 -0.540541  1.544118   
3      0.636364  0.000000 -0.188623  0.781481 -0.265116 -0.150150 -0.375000   
4      0.630303 -0.045455 -2.061377  0.774074 -0.097674 -0.286787 -0.316176   
...         ...       ...       ...       ...       ...       ...       ...   
30195  0.878788  3.590909  0.832335  0.618519 -0.418605  0.563063  1.551471   
30196  1.000000  3.636364 -0.348802  1.203704  2.776744  0.617117  0.661765   
30197 -0.569697 -0.045455 -0.173653 -0.625926 -0.404651 -0.136637 -0.588235   
30198 -0.333333  0.000000  0.425150  0.625926 -0.055814  0.564565  1.250000   
30199  0.496970  0.000000  1.393713  0.633333  2.604651  1.307808 -0.220588   

         저녁통화요금     밤통화시간     밤통화횟수     밤통화요금  상담전화건수  
0      0.848485  0.300898  1.629630  1.527261     0.0  
1      1.328788  1.197605  0.748148  1.490699     0.0  
2      1.439394  0.568862  1.629630 -0.051315    -2.0  
3      0.087879 -0.583832  0.933333  0.017960    -2.0  
4      0.721212  0.303892  0.851852 -0.402822     6.0  
...         ...       ...       ...       ...     ...  
30195  0.993939 -0.520958 -0.311111  0.012829     0.0  
30196  1.436364  0.673653  0.703704 -0.179602     0.0  
30197 -0.166667  0.760479 -0.096296 -0.311738     0.0  
30198  0.842424  0.570359  0.733333  0.756895     0.0  
30199  0.842424  0.693114  1.592593 -0.179602    -2.0  

[30200 rows x 12 columns]

In [11]:
y = call_data[['전화해지여부']]
result = pd.concat([call,y], axis=1)
result

가입일   음성사서함이용    주간통화시간    주간통화횟수    주간통화요금    저녁통화시간    저녁통화횟수  \
0      1.278788 -0.045455 -2.017964 -0.181481 -0.162791  0.387387 -0.323529   
1     -0.703030  3.590909  1.345808  1.522222  2.460465  0.396396  1.573529   
2     -0.151515  1.227273  0.724551  1.522222  0.158140 -0.540541  1.544118   
3      0.636364  0.000000 -0.188623  0.781481 -0.265116 -0.150150 -0.375000   
4      0.630303 -0.045455 -2.061377  0.774074 -0.097674 -0.286787 -0.316176   
...         ...       ...       ...       ...       ...       ...       ...   
30195  0.878788  3.590909  0.832335  0.618519 -0.418605  0.563063  1.551471   
30196  1.000000  3.636364 -0.348802  1.203704  2.776744  0.617117  0.661765   
30197 -0.569697 -0.045455 -0.173653 -0.625926 -0.404651 -0.136637 -0.588235   
30198 -0.333333  0.000000  0.425150  0.625926 -0.055814  0.564565  1.250000   
30199  0.496970  0.000000  1.393713  0.633333  2.604651  1.307808 -0.220588   

         저녁통화요금     밤통화시간     밤통화횟수     밤통화요금  상담전화건수  전화해지여부  
0      0.848485  0.300898  1.629630  1.527261     0.0       0  
1      1.328788  1.197605  0.748148  1.490699     0.0       0  
2      1.439394  0.568862  1.629630 -0.051315    -2.0       0  
3      0.087879 -0.583832  0.933333  0.017960    -2.0       0  
4      0.721212  0.303892  0.851852 -0.402822     6.0       0  
...         ...       ...       ...       ...     ...     ...  
30195  0.993939 -0.520958 -0.311111  0.012829     0.0       0  
30196  1.436364  0.673653  0.703704 -0.179602     0.0       0  
30197 -0.166667  0.760479 -0.096296 -0.311738     0.0       0  
30198  0.842424  0.570359  0.733333  0.756895     0.0       1  
30199  0.842424  0.693114  1.592593 -0.179602    -2.0       0  

[30200 rows x 13 columns]

In [12]:
result.columns

Index(['가입일', '음성사서함이용', '주간통화시간', '주간통화횟수', '주간통화요금', '저녁통화시간', '저녁통화횟수',
       '저녁통화요금', '밤통화시간', '밤통화횟수', '밤통화요금', '상담전화건수', '전화해지여부'],
      dtype='object')

- 데이터를 학습하기 위해서 데이터를 나눠서 학습시켜야 한다.
- train, test split 진행
- 교차검증 cross_validate
- 교차검증이란, split 랜덤으로 나눠서 kfold, Skfold

In [13]:
df_train = result[['가입일', '음성사서함이용', '상담전화건수', '주간통화시간', '저녁통화시간', '밤통화시간',
       '주간통화횟수', '저녁통화횟수', '밤통화횟수', '주간통화요금', '저녁통화요금', '밤통화요금']]
df_y = result['전화해지여부']

In [14]:
df_train

가입일   음성사서함이용  상담전화건수    주간통화시간    저녁통화시간     밤통화시간    주간통화횟수  \
0      1.278788 -0.045455     0.0 -2.017964  0.387387  0.300898 -0.181481   
1     -0.703030  3.590909     0.0  1.345808  0.396396  1.197605  1.522222   
2     -0.151515  1.227273    -2.0  0.724551 -0.540541  0.568862  1.522222   
3      0.636364  0.000000    -2.0 -0.188623 -0.150150 -0.583832  0.781481   
4      0.630303 -0.045455     6.0 -2.061377 -0.286787  0.303892  0.774074   
...         ...       ...     ...       ...       ...       ...       ...   
30195  0.878788  3.590909     0.0  0.832335  0.563063 -0.520958  0.618519   
30196  1.000000  3.636364     0.0 -0.348802  0.617117  0.673653  1.203704   
30197 -0.569697 -0.045455     0.0 -0.173653 -0.136637  0.760479 -0.625926   
30198 -0.333333  0.000000     0.0  0.425150  0.564565  0.570359  0.625926   
30199  0.496970  0.000000    -2.0  1.393713  1.307808  0.693114  0.633333   

         저녁통화횟수     밤통화횟수    주간통화요금    저녁통화요금     밤통화요금  
0     -0.323529  1.629630 -0.162791  0.848485  1.527261  
1      1.573529  0.748148  2.460465  1.328788  1.490699  
2      1.544118  1.629630  0.158140  1.439394 -0.051315  
3     -0.375000  0.933333 -0.265116  0.087879  0.017960  
4     -0.316176  0.851852 -0.097674  0.721212 -0.402822  
...         ...       ...       ...       ...       ...  
30195  1.551471 -0.311111 -0.418605  0.993939  0.012829  
30196  0.661765  0.703704  2.776744  1.436364 -0.179602  
30197 -0.588235 -0.096296 -0.404651 -0.166667 -0.311738  
30198  1.250000  0.733333 -0.055814  0.842424  0.756895  
30199 -0.220588  1.592593  2.604651  0.842424 -0.179602  

[30200 rows x 12 columns]

In [15]:
df_y

0        0
1        0
2        0
3        0
4        0
        ..
30195    0
30196    0
30197    0
30198    1
30199    0
Name: 전화해지여부, Length: 30200, dtype: int64

In [16]:
model = [DecisionTreeClassifier(), RandomForestClassifier(), LogisticRegression()]
name = ['DT','RF','LR']

for model, name in zip(model, name):
    print('########## 사용하는 알고리즘',name,'########')
    for score in ['accuracy','precision','recall','f1']:
        print(score)
        print('--')
        print(cross_val_score(model, df_train, df_y, scoring=score, cv=3 ))

########## 사용하는 알고리즘 DT ########
accuracy
--
[0.87851396 0.88725539 0.87929664]
precision
--
[0.44386423 0.48161765 0.44741533]
recall
--
[0.47287523 0.46925859 0.45027125]
f1
--
[0.45704163 0.47865577 0.45143885]
########## 사용하는 알고리즘 RF ########
accuracy
--
[0.91059899 0.91089699 0.91138486]
precision
--
[0.69512195 0.73694779 0.71653543]
recall
--
[0.31103074 0.32007233 0.32730561]
f1
--
[0.43117536 0.4378921  0.42964824]
########## 사용하는 알고리즘 LR ########
accuracy
--
[0.89013609 0.89013609 0.89012517]
precision
--


C:\Users\dlagm\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\dlagm\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\dlagm\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[0. 0. 0.]
recall
--
[0. 0. 0.]
f1
--
[0. 0. 0.]


### 최종 정리 RF, F1 score
- [0.43117536 0.4378921  0.42964824] 0.4329

In [17]:
print((0.43117536 + 0.4378921 + 0.42964824)/3)

0.43290523333333336
